name: ci

on:
  push:
    branches:
     - main
    paths-ignore:
      - '.vscode/**'
      - 'example/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - '.vscode/**'
      - 'example/**'
      - '*.md'

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: package.json

      - name: Install dependencies
        run: |
          npm ci

      - name: Lint code
        run: |
          npm run lint

  test:
    name: Test
    needs: 
      - lint
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: package.json

      - name: Install dependencies
        run: |
          npm ci

      - name: Run tests
        run: |
          npm run coverage:ci

      - name: Coverage
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-path: ./coverage.txt
          junitxml-path: ./junit.xml

  build:
    name: Build
    needs: 
      - test
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: package.json

      - name: Install dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run build:prod