name: ci

on:
  push:
    branches:
     - main
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  dependency-review:
      name: Dependency Review
      if: github.event_name == 'pull_request'
      runs-on: ubuntu-latest
      permissions:
        contents: read
      steps:
          - name: Check out repo
            uses: actions/checkout@v4
            with:
              persist-credentials: false

          - name: Dependency review
            uses: actions/dependency-review-action@v3

  check-licenses:
    name: Check licenses
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: package.json

      - name: Install
        run: |
          npm install --ignore-scripts

      - name: Check licenses
        run: |
          npx license-checker --production --summary --onlyAllow="0BSD;Apache-2.0;BSD-2-Clause;BSD-3-Clause;ISC;MIT;"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: package.json

      - name: Install
        run: |
          npm install --ignore-scripts

      - name: Lint code
        run: |
          npm run lint

  test:
    needs: 
      - lint
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    strategy:
      matrix:
        node-version: [16, 18, 20]
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package.json

      - name: Install
        run: |
          npm install --ignore-scripts

      - name: Run tests
        run: |
          npm run coverage